### ISSUE TITLE
Including Language Server Features

### ISSUE THREAD

**Issue by raulchedrese** [stollcri/elixir.novaextension#5]
Hey @stollcri @optikfluffel,

Any plans to include Language Server functionality in this extension? I think it would be great if users only had to install a single extension to get all the Elixir functionality they want. I've been working on an Elixir Language Server extension https://github.com/raulchedrese/nova-elixir-ls. If you are interested I'd love to see these two projects merged.

**Comment by optikfluffel** [comment]
I'm all for it 👍

**Comment by stollcri** [comment]
I originally attempted to include language server support in an early Nova beta, but I ran into troubles and dropped the idea. Your project looks great though. I'm satisfied with the scope of this extension and its lack of external dependencies, but please feel free to pull the code into your project. Good luck!
